In [1]:
import numpy as np


In [2]:
np.__version__

'2.3.1'

In [4]:
## cover list to array
lst= [1,2,34,5,6,5, "adity"]
arr= np.array(lst)

In [9]:
print(arr)
print(type(arr))

['1' '2' '34' '5' '6' '5' 'adity']
<class 'numpy.ndarray'>


In [10]:
arr= np.array(list(range(1,22)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [12]:
arr= np.arange(1,22)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])